### ISSUE TITLE
WebpackBundleLookupError in version 1.0.0 when files outside of entry points change

### ISSUE THREAD

**Issue by DrMeers** [django-webpack/django-webpack-loader#276] opened 2021-05-17 01:24 UTC
I've recently upgraded to version `1.0.0` of `django_webpack_loader` and `webpack-bundle-tracker`.

I have a project set up something like:

```
- frontend/
  - webpack.config.js
  - assets/
  - cypress/
```

The config includes:

```
entry: {
  index: ['./assets/js/index.jsx'],
},
```

When I edit files in the `cypress` directory, while running `webpack-dev-server`, no rebuild is triggered since the files aren't within the `index` entry point, but a new stats JSON is generated, and `django_webpack_loader` blows up with: `WebpackBundleLookupError: Cannot resolve bundle index`

Python error looks like this:

<img width="739" alt="Screen Shot 2021-05-17 at 11 20 36 am" src="https://user-images.githubusercontent.com/48157/118420340-f5b40c80-b701-11eb-9b06-23468b61ade0.png">

Do I need to change my configuration to somehow avoid new stats files getting generated when I edit files in `frontend/cypress`, or is this a bug? I couldn't find any `exclude` or `ignore` options in `webpack-bundle-tracker`. Didn't seem to be an issue with previous versions of these packages.

**Comment by DrMeers** [comment] 2021-05-17 01:49
> Didn't seem to be an issue with previous versions of these packages.

Confirmed downgrading to `"webpack-bundle-tracker": "^1.0.0-alpha.1"` and `git+https://github.com/oleggromov/django-webpack-loader.git@164e7e8753` works correctly.

Unrelated, but I also noticed I need to change relative path location for the stats file between `1.0.0-alpha.1` and `1.0.0` though I didn't see any mention of that anywhere:

```
-  new BundleTracker({ filename: '../webpack-stats.dev.json' }),
+  new BundleTracker({ filename: './webpack-stats.dev.json' }),
```

Not sure if any issue should be created for adding that to the docs, or if it's a regression/bug?

**Comment by fjsj** [comment] 2021-05-27 14:17
<div class="js-discussion js-socket-channel ml-0 pl-0 ml-md-6 pl-md-3" data-channel="eyJjIjoibWFya2VkLWFzLXJlYWQ6Mzk3OTg5IiwidCI6MTYyMjEyNDgyNn0=--d619066932caa68ff2864846984bd5efd8ea52191e2a45744113e3653e764004" data-channel-target="MDU6SXNzdWU3MzM4NDE1NTI=" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 16px !important; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box;"><div style="box-sizing: border-box;"><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0OTY3MjgxNg==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0OTY3MjgxNg==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0OTY3MjgxNg==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-849672816" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists current-user" data-body-version="2afb80f74cded46406d21d0a8f13ec4a29d6cd460c750a4852ebc9b210301a15" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border-color: var(--color-box-border-info); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">Thanks, we'll be checking this tomorrow</task-lists></div><form class="js-comment-update" id="issuecomment-849672816-edit-form" action="https://github.com/django-webpack/webpack-bundle-tracker/issue_comments/849672816" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div style="box-sizing: border-box;"><div class="js-timeline-marker js-socket-channel js-updatable-content" id="partial-timeline" data-channel="eyJjIjoiaXNzdWU6NzMzODQxNTUyIiwidCI6MTYyMjEyNTAyMX0=--f11f956e420552a66886a90d867fa1bc6feeaa22a3b87aa2313cc4d4b73ce8dd" data-url="/_render_node/MDU6SXNzdWU3MzM4NDE1NTI=/issues/unread_timeline?variables%5BdeferCommitBadges%5D=false&amp;variables%5BdeferStatusCheckRollups%5D=false&amp;variables%5BdeferredCommentActions%5D=true&amp;variables%5BhasFocusedReviewComment%5D=false&amp;variables%5BhasFocusedReviewThread%5D=false&amp;variables%5BtimelinePageSize%5D=30&amp;variables%5BtimelineSince%5D=2021-05-27T14%3A16%3A59Z" data-last-modified="Thu, 27 May 2021 14:16:59 GMT" data-gid="MDU6SXNzdWU3MzM4NDE1NTI=" style="box-sizing: border-box;"></div></div></div></div></div><span id="issue-comment-box" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></span><span style="color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div class="discussion-timeline-actions" style="box-sizing: border-box; background-color: var(--color-bg-canvas); border-top: 2px solid var(--color-border-primary); color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="timeline-comment-wrapper timeline-new-comment js-comment-container js-targetable-element  ml-0 pl-0 ml-md-6 pl-md-3" id="issuecomment-new" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 56px; position: relative; margin-top: 16px; margin-bottom: 0px;"><div class=" d-none d-md-block" style="box-sizing: border-box; display: block !important;"><br class="Apple-interchange-newline"></div></div></div>

**Comment by fjsj** [comment] 2021-05-28 19:50
@DrMeers could you please inform the webpack version you're using?

**Comment by DrMeers** [comment] 2021-05-28 21:17
this was on `webpack@4.43.0`

**Comment by joaopslins** [comment] 2021-05-28 21:20
@DrMeers thanks for the info.

Would you be able to share more configurations about your setup? Like webpack.config.js and webpack-dev-server setup? I'm having some trouble reproducing this issue.

**Comment by DrMeers** [comment] 2021-05-28 21:24
`webpack.dev.config.js`:

```
const webpack = require('webpack')
const BundleTracker = require('webpack-bundle-tracker')
const HtmlWebpackPlugin = require('html-webpack-plugin')

const config = require('./webpack.base.config.js')

const webpack_dev_url = process.env.WEBPACK_DEV_URL || 'http://localhost:8080'

config.devtool = 'inline-source-map'

config.entry.index = ['react-hot-loader/patch', ...config.entry.index]

config.output.publicPath = `${webpack_dev_url}/`
// config.devServer =  -- see server.js WebpackDevServer options

config.resolve = {
  ...(config.resolve || {}),
  alias: {
    ...config.resolve.alias,
    'react-dom': '@hot-loader/react-dom',
  },
}

config.module.rules[0].use[0].options.plugins.unshift('react-hot-loader/babel')

config.plugins = config.plugins.concat([
  new webpack.HotModuleReplacementPlugin(),
  new webpack.NoEmitOnErrorsPlugin(), // don't reload if there is an error
  new BundleTracker({ filename: '../webpack-stats.dev.json' }),
  new HtmlWebpackPlugin({
    templateContent:
      '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Site Title</title></head><body><div id="app"></div></body></html>',
    favicon: './assets/img/favicon.ico',
  }),
])

config.mode = 'development'

module.exports = config
```

`webpack.base.config.js`:

```
const webpack = require('webpack')
const path = require('path')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const autoprefixer = require('autoprefixer')

module.exports = {
  context: __dirname,

  entry: {
    index: ['./assets/js/index.jsx'],
  },

  output: {
    path: path.resolve('./webpack_bundles/'),
    filename: '[name]-[hash].js',
  },

  plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        eslint: {
          failOnWarning: false,
          failOnError: true,
        },
      },
    }),
    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // both options are optional
      filename: '[name]-[hash].css',
      chunkFilename: '[id]-[hash].css',
    }),
  ],

  module: {
    rules: [
      {
        // keep jsx first
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              plugins: [
                // BEWARE use config.module.rules[0].use[0].options.plugins
                // in webpack.dev.config.js!
                '@babel/proposal-class-properties',
                '@babel/proposal-object-rest-spread',
              ],
              presets: ['@babel/env', '@babel/react'],
            },
          },
          {
            loader: 'eslint-loader',
            options: {
              // fix: true,
            },
          },
        ],
      },
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.(scss|css)$/,
        use: [
          // fallback to style-loader in development
          process.env.NODE_ENV !== 'production'
            ? 'style-loader'
            : MiniCssExtractPlugin.loader,
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              plugins: () => [autoprefixer],
            },
          },
          {
            loader: 'sass-loader',
            options: {
              data: '@import "variables";',
              includePaths: [path.resolve(__dirname, './assets/css')],
            },
          },
        ],
      },
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader?limit=10000&minetype=application/font-woff',
      },
      {
        test: /\.(jpg|png|pdf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader',
      },
      {
        test: /\.(otf|ttf)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'base64-inline-loader?limit=1000&name=[name].[ext]',
      },
    ],
  },

  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'assets/js'),
      components: path.resolve('assets/js/components'),
    },
    modules: ['node_modules', 'bower_components'],
    extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
  },
}
```

`server.js`:

```
const webpack = require('webpack')
const WebpackDevServer = require('webpack-dev-server')
const config = require('./webpack.dev.config')

const PORT = parseInt(config.output.publicPath.split(':')[2], 10)

new WebpackDevServer(webpack(config), {
  publicPath: config.output.publicPath,
  index: 'index.html',
  disableHostCheck: true,
  sockHost: 'localhost',
  sockPort: PORT,
  hot: true,
  inline: true,
  historyApiFallback: true,
  headers: {
    'Access-Control-Allow-Origin': '*',
  },
}).listen(PORT, '0.0.0.0', (err, result) => {
  if (err) {
    console.log(err)
  }

  console.log(`Listening at 0.0.0.0:${PORT}...`)
})
```

**Comment by joaopslins** [comment] 2021-05-28 21:25
Awesome, thanks for the quick reply! Will be giving a look at this soon.

**Comment by DrMeers** [comment] 2021-05-28 21:33
Thank you!

**Comment by joaopslins** [comment] 2021-06-04 22:41
Hi @DrMeers,

I've tried to reproduce the issue with the config files you've sent but I wasn't able to. I think there might be more variables involved that we should look at.

>When I edit files in the cypress directory, while running webpack-dev-server, no rebuild is triggered since the files aren't within the index entry point, but a new stats JSON is generated

This feels odd to me because the stats file are tied with the builds, so it isn't expected for it to change without a new build... From your image, I see the output file was changed to `index.ts.js`. This might be somehow related with the use of Cypress, although I also don't have any strong reasoning to back that up... 

I don't think it's an issue with the `django-webpack-loader` because the stats file has changed, this is owned by `webpack-bundle-tracker`, and that repo had minimal changes from `1.0.0-alpha.0` and `1.0.0`. If I had to guess, I'd say something is overwriting the stats file with changes from other directory, as if `new BundleTracker` is being used somewhere else.

Could you check if either `new BundleTracker` is used elsewhere, or if `webpack.dev.config` is being extended in another place?  
Also I assume you aren't running cypress at the same time, but if so, could you test with only our application dev server running?

This is a longshot but the only thing that might make sense to me is that you might be using webpack in Cypress and the `BundleTracker` plugin is being used there by accident, overriding the stats file. I see webpack can be used in Cypress with https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor.

Also more information that might help are:
- The command to run the dev server. Usually it's `node server.js` but I'd like to confirm how your command is set up
- Your `WEBPACK_LOADER` configuration in Django settings.

**Comment by fjsj** [comment] 2023-11-29 14:30
Closing as not reproduced. Please feel free to provide more info if you face a similar issue.

**Closed by fjsj** 2023-11-29 14:30 UTC
