### ISSUE TITLE
Code Splitting

### ISSUE THREAD

**Issue by viperfx** [django-webpack/django-webpack-loader#165] opened 2018-06-11 09:54 UTC
When bundles get large, which happen fairly easily with the inclusion of React, Redux, Component libraries etc. 

The next step to reduce the file size is code splitting based on routes. 

Here is an example: 

https://reactjs.org/docs/code-splitting.html

Can this be supported by Django Webpack Loader?

**Comment by BrianHVB** [comment] 2018-06-11 21:37
I've been trying this as well. I have a multi-page application written purely in Django and plain JavaScript (with some JQuery). I want to start using React to create some shared components, but I'm struggling with finding a way to have multiple entries that can still share a code base.

I followed the `split-chunks` method that is detailed at https://webpack.js.org/guides/code-splitting/ but I can't seem to get django-webpack-loader to pick up on the bundles that Webpack produces. The same is true of the `Dynamic Imports` approach.

Please post a response if you find a solution.

**Comment by liederer** [comment] 2018-07-11 16:15
I don't know if this helps you, but this is how I get django-webpack-loader working with Vue.js (CLI in Multi-Page-Mode). In my Django template I load my `app` bundle with:
```
{% render_bundle 'chunk-vendors' 'css' %}
{% render_bundle 'app' 'css' %}

<!-- content/body -->

{% render_bundle 'chunk-vendors' 'js' %}
{% render_bundle 'app' 'js' %}
```

This is the only way how I was able to use django-webpack-loader in webpack production mode.
I was able to figure it out by looking in `webpack-stats.json`.

**Comment by viperfx** [comment] 2018-07-11 16:20
Julian, that's just code splitting via manual bundles. It's not the same as
dynamic splitting based on routes.

**Comment by liederer** [comment] 2018-07-11 17:35
Thanks for clarification! 👍

**Comment by tgdn** [comment] 2018-10-17 16:07
Any updates on this?

**Comment by superandrew** [comment] 2018-10-17 21:48
+1

**Comment by SalTor** [comment] 2018-10-29 19:36
+1

**Comment by hiimdoublej** [comment] 2018-11-02 02:32
+1

**Comment by bhrutledge** [comment] 2019-02-14 17:15
For folks encountering this issue, this seems to similar, if not identical, to #157. PR #182 has a fix waiting to be merged, but it depends on PR https://github.com/owais/webpack-bundle-tracker/pull/41. See my comment there for [relevant links and workarounds](https://github.com/owais/webpack-bundle-tracker/pull/41#issuecomment-463709521).

**Comment by harveynr** [comment] 2019-02-19 19:04
In an attempt to address this issue, I've created PR #191.  This is my 2nd PR ever so go easy.  But hopefully this helps someone as I got frustrated with the chunk names constantly changing which meant manually updating the `render_bundle` tags.

**Comment by rocchidavide** [comment] 2019-06-28 08:21
> I don't know if this helps you, but this is how I get django-webpack-loader working with Vue.js (CLI in Multi-Page-Mode). In my Django template I load my `app` bundle with:
> 
> ```
> {% render_bundle 'chunk-vendors' 'css' %}
> {% render_bundle 'app' 'css' %}
> 
> 
> 
> {% render_bundle 'chunk-vendors' 'js' %}
> {% render_bundle 'app' 'js' %}
> ```
> 
> This is the only way how I was able to use django-webpack-loader in webpack production mode.
> I was able to figure it out by looking in `webpack-stats.json`.

Julian, how do you solve the problem that, with `npm run serve`, including {% render_bundle 'chunk-vendors' 'js' %} causes `Cannot resolve bundle chunk-vendors.` error?

**Comment by iamsavinay** [comment] 2019-10-20 04:58
Comment out this line in `vue.config.js` 
`config.optimization.splitChunks(false);`
to
`// config.optimization.splitChunks(false);`

Webpack automatically does required task

**Comment by EugeneDae** [comment] 2020-05-26 14:06
> Maybe a simple and clean solution was just adding support to pass a special bundle_name like 'all', which would include all chunks declared on webpack-stats.json:

If any of you use Vue CLI and struggle with code-splitting, you might want to check out this demo:
https://github.com/EugeneDae/django-vue-cli-webpack-demo

Its another approach of including Webpack assets by including the HTML file generated by html-webpack-plugin into Django templates (via `{% extends %}`).

It should also work for non-Vue Webpack projects.

**Comment by ghadjigeorghiou** [comment] 2020-07-08 06:31
> `Cannot resolve bundle chunk-vendors.` error?

Did you manage to resolve this?

**Comment by robert8888** [comment] 2021-05-04 01:52
This fork of webpack loader 
>https://github.com/MrP01/django-webpack-loader

And this trucker 
>https://www.npmjs.com/package/webpack4-bundle-tracker

using above combination we can use:
```
{% load render_entrypoint from webpack_loader %}
{% render_entrypoint 'index' %}
```
what render whole entry point with all chunks no matter how they are splitted.

**Comment by fjsj** [comment] 2021-05-13 19:22
Due to entrypoints-based behavior of 1.0.0 (after merging #232), I think we can now close this issue. Could you please check @joaopslins?

**Comment by joaopslins** [comment] 2021-05-14 22:33
Hi folks,

It looks like Code Splitting is working in version 1.0.0. You just need to set the `publicPath` config in `output` to inform webpack where to find the bundle. 

This is needed because `django-webpack-loader` actually doesn't do anything with the dynamically generated bundles: They are fetched directly from Javascript.

I managed to get it working with the following example: (webpack v4)

```javascript
// src/principal.js
function getComponent() {
  return import(/* webpackChunkName: "lodash" */ 'lodash').then(({ default: _ }) => {
    const element = document.createElement('div');

    element.innerHTML = _.join(['Hello', 'webpack'], ' ');

    return element;
  }).catch(error => 'An error occurred while loading the component');
}


getComponent().then((component) => {
  document.body.appendChild(component);
})
```

```javascript
// webpack.config.js
module.exports = {
  context: __dirname,
  entry: {
    principal: './src/principal',
  },
  output: {
    path: path.resolve('./dist/'),
    // publicPath should match your STATIC_URL config.
    // This is required otherwise webpack will try to fetch 
    //  our chunk generated by the dynamic import from "/" instead of "/dist/".
    publicPath: '/dist/', 
    chunkFilename: '[name].bundle.js',
    filename: "[name]-[hash].js"
  },

  plugins: [
    new BundleTracker({ filename: './webpack-stats.json' })
  ]
}
```

```html
<!-- index.html -->
{% load render_bundle from webpack_loader %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>
    <p>This is my page</p>

    {% render_bundle 'principal' 'js' %}
  </body>
</html>
```

Using Webpack 5 works by changing `filename: "[name]-[hash].js"` to `filename: "[name]-[fullhash].js"` and removing `/* webpackChunkName: "lodash" */`, which is not needed anymore.

I haven't tested with framework specific techniques -- like Route based code splitting in React or Vue -- but I believe it should work. If not, please provide a reproducible example so we can investigate. Thanks.

@fjsj This is probably something that we should have on README and/or a recipe as an example on how to do that.

**Closed by joaopslins** 2021-05-14 22:33 UTC

**Comment by EthanZeigler** [comment] 2021-07-18 18:50
This has a problem. While it's great that it pulls in dependent bundles, it also pulls in shared chunks more than once causing duplicate module import problems. In my case, for bootstrap. Going to make a issue for it.

**Comment by fjsj** [comment] 2021-10-03 22:14
@EthanZeigler that problem was solved via https://github.com/django-webpack/django-webpack-loader/pull/297
i.e., use `{% render_bundle "app2" skip_common_chunks=True %}`
