### ISSUE TITLE
Get Blank page

### ISSUE THREAD

**Issue by axwack** [django-webpack/django-webpack-loader#159] opened 2018-04-17 13:21 UTC
I have loaded and followed this correctly and the bundles load but I get a blank screen when using the Django server. Any ideas?

**Comment by owais** [comment] 2018-04-19 10:14
Have you tried to view source of your HTML and see if the JS tabs and rendered properly? If you say bundles are loading then the issue must be with you JS code which is out of scope of this project. That said, share a stripped down, hello world version of your app here and I can try to help if I can.

**Comment by axwack** [comment] 2018-04-19 17:39
Nothing gets rendered. I even did this with one of the older tutorials. How can I send you the hello world? Do you want me to share the JS files?

**Comment by owais** [comment] 2018-04-19 18:13
This is too vague. What do you mean by "nothing". Is entire HTML page empty, are the script pages missing, does your JS app not render it's UI but django sends down the HTML? 

>  How can I send you the hello world? Do you want me to share the JS files?

Normally people create temporary repositories on github to share such code but it won't be useful if this is an issue in your JS app. From your earlier comment, it seems the bundles are loading. Django-webpack-loader's responsibility ends there. If the bundles do load, it might be an issue with your JS code.

**Comment by axwack** [comment] 2018-04-19 19:07
Have you ever seen this error? 

Module build failed: Error: Couldn't find preset "react-app" relative to directory "/Users/vincentlee/Documents/Development/arlo_react/frontend"

**Comment by owais** [comment] 2018-04-19 20:36
Looks like "react-app" package is missing. Is this supposed to be an npm package that you install or a custom one?

**Comment by emrehayirci** [comment] 2018-10-11 22:54
I also experienced the same problem while integrating react app (that I created with create-react-app) to my Django application. When I looked closely to my stats file I realized that my webpack-config generated 3 files: 0.chunk.js, main.bundle.js, bundle.js I solved the problem by importing all of them

**Comment by jaisonjjames** [comment] 2018-11-07 05:43
> This is too vague. What do you mean by "nothing". Is entire HTML page empty, are the script pages missing, does your JS app not render it's UI but django sends down the HTML?
> 
> > How can I send you the hello world? Do you want me to share the JS files?
> 
> Normally people create temporary repositories on github to share such code but it won't be useful if this is an issue in your JS app. From your earlier comment, it seems the bundles are loading. Django-webpack-loader's responsibility ends there. If the bundles do load, it might be an issue with your JS code.

I am also experiencing the same problem with webpack 4, it seems like every js files are generated successfully, but main.chunk.js are only rendering in the browser 0.chunk.js and bundle.js are missing, so its causes the blank page. I have posted the issue in the [StackOverflow](https://stackoverflow.com/q/53078592/1374554) but no replay.

**Comment by ehmadzubair** [comment] 2018-11-27 11:59
@emrehayirci Did you import them manually? Doesn't that defeat the purpose of using the webpack loader?

cc: @owais

**Comment by emrehayirci** [comment] 2018-11-30 08:56
@ehmadzubair Yes, for now I moved forward with importing them manually. I know it is not ideal but for now until other tasks finished this keeps me going. I am open for suggestions.

**Comment by ehmadzubair** [comment] 2018-11-30 11:44
@emrehayirci I had a workaround for this. Check #183

**Comment by emrehayirci** [comment] 2018-12-05 22:07
@ehmadzubair Yes this was the same workaround I mentioned above. But I am pretty sure it is not an ideal one because we are manually adding them to the template. So what happens if we prefer to increase our number of chunks? Feels something not right here.

**Comment by ajiejot** [comment] 2018-12-14 01:45
Anyone solved the problem? I still cant solve it. here is my question. https://stackoverflow.com/questions/53772300/django-reactjs-no-template-being-rendered

**Comment by oussjarrousse** [comment] 2019-02-05 14:35
I am also having the same issue. I would be thankful if anyone found a proper solution for this issue!

**Comment by fjsj** [comment] 2023-11-29 20:33
Hard to reproduce. If anyone face this again, please open a new issue. Closing this one.

**Closed by fjsj** 2023-11-29 20:33 UTC
