### ISSUE TITLE
Using Webpack splitChunks and cacheGroups

### ISSUE THREAD

**Issue by SchubmannM** [django-webpack/django-webpack-loader#157] opened 2018-04-05 17:05 UTC
Hi,
is it possible to use splitChunks and cacheGroups while having "name: false"? 

Currently I have the following webpack configuration:
`entry: {
        Homepage: './react/Homepage',
        vendors: ['react'],
    },
optimization: {
        splitChunks: {
            name: false,
            cacheGroups: {
                commons: {
                    name: 'vendors',
                    chunks: 'all',
                    test: /[\\/]node_modules[\\/]/,
                    priority: -10,
                },
            },
        },
    }`

This creates a specific chunk file called "vendors" in addition to all other chunk files that are defined as entry points ("Homepage" in this example). 

Now in order to display the entry point Homepage, i have to include both bundles via template tags into the html file:
`{% render_bundle 'vendors' %}
 {% render_bundle 'Homepage' %}`

This behaviour is quite useful, as the vendors file can be cached and so when other pages are loaded, the vendors file does not have to be downloaded again.

Now my problem: Webpack 4 recommends using `"name: false"` to optimise the loading and caching of resources across multiple entry points. By doing this, the "vendors" file can be split into multiple smaller files, and then the entry point configuration changes from:

`Entrypoint Homepage = vendors-4f65a9a5a66defc0a60b.js Homepage-4f65a9a5a66defc0a60b.js`

to 

`Entrypoint Homepage = 0-77b58caa5e7acecf0a4e.js 1-77b58caa5e7acecf0a4e.js Homepage-77b58caa5e7acecf0a4e.js`

So now instead of loading the huge vendors file with the first load, the user only has to load 2 smaller files. 

But now I cannot use the 0-hash and 1-hash files in the webpack-bundle-loader, as `{% render_bundle '0' %}` etc. cannot find these chunks (they don't have chunk names in the webpack compile summary). Additionally, the names (0, 1, etc) would change every time new dependencies get added. 

Is there a way to render complete entry points together with all their chunks? I would assume `{% render_bundle 'Homepage' %}` would look up the entry point 'Homepage' instead of the chunkname and then render all required chunks based on that.

Any suggestions? Or am I missing something?

**Comment by SchubmannM** [comment] 2018-04-10 09:13
I tried 0.4.0-beta but I couldn't see the proper bundle information. I think the webpack-bundle-tracker has to extend its stats.json file to include more information. I went through webpacks CLI documentation and found their own stats data command: 
`webpack --profile --json --config webpack.config.js > compilation-stats.json`
produces the information that would be needed in the bundle-tracker stats file:
`.....
"entrypoints": {
    "Homepage": {
      "chunks": [
        0,
        1,
        "Homepage"
      ],
      "assets": [
        "0-de629161af8ff152d740.js",
        "1-de629161af8ff152d740.js",
        "Homepage-de629161af8ff152d740.js"
      ]
    },
....`

Not sure how to proceed from here, as it seems this "feature" request is dependant on webpack-bundle-tracker providing the necessary information through the stats file.

**Comment by gfhuseyinyilmaz** [comment] 2018-04-25 01:13
Hello,

One possible solution to this is not adding name attribute to configuration. It seems like if we don't add the name attribute, generated bundle names has information about which bundle they are splitted from. Here is an example from webpack examples directory:

https://github.com/webpack/webpack/tree/master/examples/common-chunk-and-vendor-chunk

Here we have a cache group called commons:
```
				commons: {
					chunks: "initial",
					minChunks: 2,
					maxInitialRequests: 5, // The default limit is too small to showcase the effect
					minSize: 0 // This is example is too small to create commons chunks
				},
```

That cache group creates bundles like this:

```
commons~pageA~pageB~pageC.js  269 bytes       4  [emitted]  commons~pageA~pageB~pageC
      commons~pageB~pageC.js  269 bytes       5  [emitted]  commons~pageB~pageC
```
I am not sure about the details but it seems like name of those bundles has informations about which bundle they are splitted from.

**Comment by afontcu** [comment] 2018-05-02 08:40
Hi! Since Webpack 4 is concatenating every module on its bundle name, wouldn't be helpful if django-webpack-loader would track and include every bundle including the defined name?

```bash
                                        Asset      Size  Chunks             Chunk Names
                   0.69db622a08d7c6ec0ec3.css  15.3 KiB       0  [emitted]  main~somePage
        main~somePage.69db622a08d7c6ec0ec3.js  1.05 KiB       0  [emitted]  main~somePage
vendors~main~somePage.69db622a08d7c6ec0ec3.js   102 KiB       1  [emitted]  vendors~main~somePage
             somePage.69db622a08d7c6ec0ec3.js   1.2 KiB       2  [emitted]  somePage
                 main.69db622a08d7c6ec0ec3.js   1.2 KiB       3  [emitted]  main
```

Then `{% render_bundle 'main' 'js' %}` would match every js bundle including "main" in its name:

* main~somePage.69db622a08d7c6ec0ec3.js
* vendors~main~somePage.69db622a08d7c6ec0ec3.js
* main.69db622a08d7c6ec0ec3.js

Thanks!

**Comment by afontcu** [comment] 2018-05-02 09:05
I assume it'd only need to update this line in order to match all keys containing the specified bundle_name:

https://github.com/owais/django-webpack-loader/blob/master/webpack_loader/loader.py#L81 

If that's the case, I'd happily send a PR.

**Comment by beheh** [comment] 2018-05-04 00:11
@afontcu As a short fix that would work, although you do run the risk of colliding substrings (e.g. "js" included in "json"). You could check for the tilde (~), but I think the real fix would be to go the clean route as mentioned further up in this thread by having webpack-bundle-tracker explicitely expose the chunk associations.

**Comment by afontcu** [comment] 2018-05-04 06:02
Yes, that would be great and it's definitely the right solution! Let's see what happens with the webpack-bundle-tracker.

However, I think loading all the keys matching the bundle_name would be a quite solid fix using `~` as stop word, which is pretty good idea. Then, a bundle named "js" would return all bundles containing `~js~`, `js~` or `~js`, thus avoiding conflicts with "json" and so on.

Thanks for the quick response!

**Comment by littlehome-eugene** [comment] 2018-12-16 14:21
Waiting for this..

What's the best we can do with webpack4 and django-webpack-loader currently as far as `code-splitting` goes?

I'd like to use options described in https://hackernoon.com/the-100-correct-way-to-split-your-chunks-with-webpack-f8a9df5b7758

When I add the optimization for production, web page shows a blank page. 
I guess `{% render_bundle ...%}` is not picking up splitted files.

```

   optimization: {
     runtimeChunk: 'single',
     splitChunks: {
       chunks: 'all',
       maxInitialRequests: Infinity,
       minSize: 0,
       cacheGroups: {
         vendor: {
           test: /[\\/]node_modules[\\/]/,
           name(module) {
             // get the name. E.g. node_modules/packageName/not/this/part.js
             // or node_modules/packageName
             const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];

             // npm package names are URL-safe, but some servers don't like @ symbols
             return `npm.${packageName.replace('@', '')}`;
           },
         },
       },
     },
   },
```

**Comment by bhrutledge** [comment] 2019-02-14 17:15
For folks encountering this issue, this seems to similar, if not identical, to #165. PR #182 has a fix waiting to be merged, but it depends on PR https://github.com/owais/webpack-bundle-tracker/pull/41. See my comment there for [relevant links and workarounds](https://github.com/owais/webpack-bundle-tracker/pull/41#issuecomment-463709521).

**Comment by timkindberg** [comment] 2019-11-19 22:02
> However, I think loading all the keys matching the bundle_name would be a quite solid fix

It ends up being a bad fix because if the chunk name becomes too long the whole thing gets truncated, so you cannot use the chunk name as a reliable indicator. You have to actually change webpack-bundle-tracker like that #41 PR above does.

**Comment by fjsj** [comment] 2021-05-13 19:24
How does this play after entrypoint-based behavior we introduced in 1.0.0? Could you please check @joaopslins ?
Maybe this is a no-issue now.

**Comment by joaopslins** [comment] 2021-05-14 21:55
I've tested both the original case and the snippet from @littlehome-eugene and it worked correctly on version 1.0.0.

If someone has a case where you think it isn't covered by the new version, please let me know so I can try to reproduce it. Thanks.

**Closed by joaopslins** 2021-05-14 21:55 UTC
