### ISSUE TITLE
yarnpkg run build failing due to mkdirSync

### ISSUE THREAD

**Issue by cmunk** [django-webpack/django-webpack-loader#288] opened 2021-07-09 13:19 UTC
The following line (webpack-bundle-tracker/lib/index.js:89)
`fs.mkdirSync(this.outputTrackerDir, { recursive: true, mode: 0o755 });`

Causes our build to fail as the outputTrackerDir already exists:
```
yarn run v1.13.0
$ yarnpkg run clean && yarnpkg run copy:assets && yarnpkg run build:js
$ rm -rf $npm_package_build_dir
$ cp -r $npm_package_src_dir/images $npm_package_build_dir && cp $npm_package_src_dir/favicon.ico $npm_package_build_dir/ && yarnpkg update:alert
$ cp ./static/maintenance-alert.js $npm_package_build_dir/
$ webpack --mode development
Green env is set to: undefined
/git/bbd/src/green
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir '/git/bbd/src/green'
    at Object.fs.mkdirSync (fs.js:885:18)
    at BundleTrackerPlugin._writeOutput (/git/bbd/src/green/node_modules/webpack-bundle-tracker/lib/index.js:89:8)
    at BundleTrackerPlugin._handleCompile (/git/bbd/src/green/node_modules/webpack-bundle-tracker/lib/index.js:115:10)
    at SyncHook.eval [as call] (eval at create (/git/bbd/src/green/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/git/bbd/src/green/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeCompile.callAsync.err (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:665:23)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/git/bbd/src/green/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/git/bbd/src/green/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:662:28)
    at readRecords.err (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:321:11)
    at Compiler.readRecords (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:529:11)
    at hooks.run.callAsync.err (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:318:10)
    at _err0 (eval at create (/git/bbd/src/green/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at compiler.hooks.run.tapAsync (/git/bbd/src/green/node_modules/webpack/lib/CachePlugin.js:50:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/git/bbd/src/green/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/git/bbd/src/green/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:315:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/git/bbd/src/green/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/git/bbd/src/green/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:312:24)
    at processOptions (/git/bbd/src/green/node_modules/webpack-cli/bin/cli.js:353:14)
    at yargs.parse (/git/bbd/src/green/node_modules/webpack-cli/bin/cli.js:364:3)
    at Object.parse (/git/bbd/src/green/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /git/bbd/src/green/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/git/bbd/src/green/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Perhaps there should be a check for dir first, before an attempt to create it is made?

**Comment by fjsj** [comment] 2021-07-09 13:24
Hi, could you please provide the versions of your node, yarn, django-webpack-loader, webpack-bundle-tracker?

**Comment by cmunk** [comment] 2021-07-09 13:26
```
"webpack-bundle-tracker": "^1.1.0",
django-webpack-loader==1.0.0
yarnpkg --version
1.13.0
node --version
v8.10.0
```

**Comment by fjsj** [comment] 2021-07-09 13:38
Thanks. It's recommnded to keep django-webpack-loader version in sync with webpack-bundle-tracker.
Also, webpack-bundle-tracker 1.1.0 requires Node 12 or up.

But neither is a solution for this issue. For now can you solve this by manually removing the dir? We'll check what would be the best behavior here.

**Comment by cmunk** [comment] 2021-07-09 13:40
The dir itself is our codebase, so not really an option -- if I try to put it into a ./assets/ subfolder it still happens (or lala2 as in the example below):

```
(Ubuntu18.04)crmu@crmu:/git/bbd/src/green(cpe-upgrade)$ yarnpkg run build
yarn run v1.13.0
$ yarnpkg run clean && yarnpkg run copy:assets && yarnpkg run build:js
$ rm -rf $npm_package_build_dir
$ cp -r $npm_package_src_dir/images $npm_package_build_dir && cp $npm_package_src_dir/favicon.ico $npm_package_build_dir/ && yarnpkg update:alert
$ cp ./static/maintenance-alert.js $npm_package_build_dir/
$ webpack --mode development
Green env is set to: undefined
/git/bbd/src/green/lala2
/git/bbd/src/green/lala2
Error: EEXIST: file already exists, mkdir '/git/bbd/src/green/lala2'
    at Object.fs.mkdirSync (fs.js:885:18)
    at BundleTrackerPlugin._writeOutput (/git/bbd/src/green/node_modules/webpack-bundle-tracker/lib/index.js:89:8)
    at BundleTrackerPlugin._handleDone (/git/bbd/src/green/node_modules/webpack-bundle-tracker/lib/index.js:166:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/git/bbd/src/green/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/git/bbd/src/green/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:304:22)
    at Compiler.emitRecords (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:499:39)
    at emitAssets.err (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:298:10)
    at hooks.afterEmit.callAsync.err (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:485:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/git/bbd/src/green/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/git/bbd/src/green/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:482:27)
    at /git/bbd/src/green/node_modules/webpack/node_modules/neo-async/async.js:2818:7
    at done (/git/bbd/src/green/node_modules/webpack/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/git/bbd/src/green/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (/git/bbd/src/green/node_modules/webpack/lib/Compiler.js:464:33)
    at /git/bbd/src/green/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 

It's as if it has two "rounds" and the 2nd time it will notice that the folder already exists..

**Comment by cmunk** [comment] 2021-07-09 13:46
But as you say -- maybe never versions of node.js has a "smarter" `fs.mkdirSync` that can handle if a dir exists.. But if you make your code check it before calling it, then we'll be able to use it ;-)

**Comment by fjsj** [comment] 2021-07-09 13:52
@cmunk I think the problem is indeed your node version, but not because of a change of how mkdirSync handles the first/root directory existence, but because your node version doesn't support the recursive creation, so it tries always to re-create the root directory only. See that recursive has been added only on node 10 ([docs here](https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options)):
![Screenshot from 2021-07-09 10-49-07](https://user-images.githubusercontent.com/397989/125088105-7c9eb900-e0a3-11eb-8416-aedc24c76a14.png)

---
I see you just updated your last comment with a similar comment, so I'll be closing this issue for now.

**Closed** 2021-07-09 13:52 UTC
